### ISSUE TITLE
DOCS - Device Services - Enterprise "block"

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#10]
The line reads:  Enterprise-level applications, which require specific approval from Vinli, are able to manage a specific block of devices that are "owned" by the application.  I don't see where the concept of a "block" of device IDs exists.  If it does, I would expect that Device IDs being returned from a List all Devices request would be identified by their block, but there is no block attribute associated with a device or that pagination provides organization based on blocks for an enterprise application.
![platform services device service](https://cloud.githubusercontent.com/assets/13001388/8363602/9cbc1752-1b45-11e5-9a3d-9ea217f28518.png)

**Comment by JeffYounger** [comment]
Duplicate. Already fixed.
