### ISSUE TITLE
DOCS - Device Services - Get a Device - groups link

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#11]
For "Get a Device" the Response shows links: Self, Groups, Vehicles, LatestVehicle".  When I look at the device.js file, it shows links: Self, Vehicles, Latest Vehicle.  I'm thinking that Groups should be removed from the doc.
![platform service device service get device](https://cloud.githubusercontent.com/assets/13001388/8364553/c0b8f646-1b4c-11e5-8d10-0e12230cddfc.png)

**Comment by JeffYounger** [comment]
Need QA to look at this, and tell me how to edit it.

**Comment by paulqlove** [comment]
Jeff, 
Groups was removed from  GET /devices/:id 
![screen shot 2015-11-18 at 11 17 49 am](https://cloud.githubusercontent.com/assets/8879375/11248359/5fb3bd74-8de6-11e5-8971-8d9813c8fde0.png)

**Comment by JeffYounger** [comment]
Fixed.
