### ISSUE TITLE
DOCS - Rule Services - Overview - incomplete bullet

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#12]
Rule Services overview file, Rules heading, In a nutshell 3rd bullet has an incomplete thought:  ...For instance, if a device

![platform - rule service overview](https://cloud.githubusercontent.com/assets/13001388/8414193/d6364142-1e5b-11e5-8b8d-68149da1fa74.png)

**Comment by JeffYounger** [comment]
Fixed
