### ISSUE TITLE
DOCS - Event Service - Get Events - Response example has a typo

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#14]
The Response pagination has the parameter "remaining".  In the platform's transaction service, the "get all transactions" response also uses streaming pagination, however it has parameter " remainingCount" and not "remaining".  Which one is correct?
![event service - get events - response](https://cloud.githubusercontent.com/assets/13001388/8417987/c4bcd07e-1e75-11e5-88bb-c6ac4afe856c.png)

**Comment by rubyb** [comment]
Update:  I went and looked at the code and "remaining" is correct in both the transaction service and the event service for streaming pagination.  The example needs to be updated for the transaction service to reflect "remaining" and not "remainingCount" in the response example for Transaction Services.

**Comment by JeffYounger** [comment]
Updated.
