### ISSUE TITLE
DOCS - General - Authentication - typo

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#20]
Authentication section, 3rd paragraph:  Each request must include the App ID and App Secret in the Authentorization... should be spelled Authorization
![screen shot 2015-07-22 at 3 15 51 pm](https://cloud.githubusercontent.com/assets/13001388/8836270/7548b3ec-3085-11e5-89a5-e2dbbd0710f9.png)

**Comment by JeffYounger** [comment]
Corrected spelling.
