### ISSUE TITLE
DOCS - Pagination - Update reference to chronological sort order

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#21]
Pagination does not sort in chronological order for resource list pagination or oldest to most recent order for streaming pagination.  Instead, it has been decided to use time series ordering where the first item in the list should be the "latest or most recent.  For example - vehicles are returned in order based on most recently used. 
A request to list all vehicles for a device would look like this:
GET https://platform-dev.vin.li/api/v1/devices/fe4bbc20-cc90-11e3-8e05-f3abac5b6b21/vehicles

In the response, the first vehicle in the list has the same vehicleID as sending the request with the "_latest" parameter.

GET https://platform-dev.vin.li/api/v1/devices/fe4bbc20-cc90-11e3-8e05-f3abac5b6b21/vehicles/_latest

In the response, the vehicleID is the same as the first vehicle in the results from the List all vehicles request"

**Comment by JeffYounger** [comment]
Updated, but I'd like a developer to review this.

**Comment by dofchinick** [comment]
Link: http://docs.vin.li/en/latest/web/general/pagination.html?highlight=pagination

**Comment by n-boehmisch** [comment]
document conveys non-chronological pagination.
