### ISSUE TITLE
DOCS - Vehicle Service - List All Vehicles for a Device - Update

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#22]
List All of a Device's Vehicles

Returns the vehicles associated with the given device in chronological order.

Update to read ...given device in time series order.

![screen shot 2015-07-23 at 9 26 24 am](https://cloud.githubusercontent.com/assets/13001388/8852913/83e260c2-311d-11e5-9930-0518e307f451.png)

**Comment by JeffYounger** [comment]
Fixed.
