### ISSUE TITLE
DOCS - Trip-Service - Get Details of a Trip - update verbiage

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#29]
Verbiage states:
For each trip, more detailed information regarding overall trip statistics is available here. This includes start and stop location as well as a few other statistical information which may be of interest. These items include: <stats>

All of the detailed information listed in the above verbiage is available via the get trips by device or get trips by vehicle.

**Comment by ehis** [comment]
@pkinney

**Comment by rubyb** [comment]
Fixed!
![screen shot 2015-08-31 at 8 33 48 am](https://cloud.githubusercontent.com/assets/13001388/9579846/172d53ee-4fbb-11e5-8e94-fced1ffaab7b.png)
