### ISSUE TITLE
DOCS - Event-Services - Subscriptions - Typos

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#30]
Notification Payload section - verbiage below the example, second paragraph starts like this and has 2 typos - Notification and representation:

In the example above, the Subscription triggered is associated with a Rule. In this case, additional information is made available in the Notificaiton including a reprsentation of the Rule in the meta property.

![screen shot 2015-07-30 at 4 45 25 pm](https://cloud.githubusercontent.com/assets/13001388/8996165/ab57ee2e-36db-11e5-9401-309d1ad1a40e.png)

**Comment by JeffYounger** [comment]
Fixed.
