### ISSUE TITLE
DOCS - Event-Services - Subscriptions - Delete a Subscription - typo

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#31]
Delete a Subscription section's verbiage starts with a typo in Subscription:

Subscriptins are primarily...

![screen shot 2015-07-30 at 5 57 06 pm](https://cloud.githubusercontent.com/assets/13001388/8997246/c85be7e2-36e4-11e5-9854-7abe74cdd01f.png)

**Comment by JeffYounger** [comment]
Fixed.
