### ISSUE TITLE
DOCS - Telemetry - Add min/max acceleration stats to messages response

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#33]
"accel" : {
        "min accel": nn,
        "max accel": nn,  
      }

**Comment by JeffYounger** [comment]
The above doesn't accord with what I see in the code. QA pleas help.

**Comment by dofchinick** [comment]
@kturney: can you take a look and help clarify for Jeff?

**Comment by gangstead** [comment]
This issue was moved to vinli/pre-release-docs#1
