### ISSUE TITLE
DOCS - Telemetry - GET a Specific Telemetry Message - doc request needs to be updated

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#34]
Request is showing old style format and needs to be updated to show:
https://telemetry-dev.vin.li/api/v1/messages/{messageID}
![screen shot 2015-08-04 at 12 55 27 pm](https://cloud.githubusercontent.com/assets/13001388/9068273/2b886194-3aa8-11e5-9ea1-1e80f1058e6f.png)

**Comment by JeffYounger** [comment]
Docs had deprecated route and JSON. I've updated it. Might have been updates to telemetry JSON. Need QA to check it.

**Comment by JeffYounger** [comment]
See this link: http://docs.vin.li/en/latest/web/telemetry-services/device-messages.html

**Comment by n-boehmisch** [comment]
The doc is correct for the generic nature of a specific telemetry message.
