### ISSUE TITLE
DOCS - Diagnostic Services - dtc-history.rst - response has 2 "limit" parameters

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#35]
Get the list of all DTC Codes for a Device - in the response, scroll down to the pagination meta data.
There are 2 "limit" parameters - on is set to the default and the other is set to the maximum
![screen shot 2015-08-06 at 3 31 23 pm](https://cloud.githubusercontent.com/assets/13001388/9122772/c8a208aa-3c50-11e5-8b11-5cdba0cfb919.png)

**Comment by JeffYounger** [comment]
Removed maximum parameter.
