### ISSUE TITLE
DOCS - Rule Service - typo index.rst file

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#40]
Last sentence: ...but it's import to not that only those parameters with a decimal dataType are usable in Rules.  - "not" should be "note"

![screen shot 2015-08-27 at 5 38 27 pm](https://cloud.githubusercontent.com/assets/13001388/9535039/ed03f7b0-4ce2-11e5-9718-c32394902b83.png)

**Comment by rubyb** [comment]
Last paragraph - need to add a right parenthesis to close the thought and a period to end the sentence.

**Comment by JeffYounger** [comment]
Fixed.
