### ISSUE TITLE
DOCS - Rule Service - missing parameters section

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#41]
Doc states:  More information about these parameters can be found in the "Parameters" section above, but it is important...  
![screen shot 2015-08-27 at 5 44 52 pm](https://cloud.githubusercontent.com/assets/13001388/9535111/9456fa30-4ce3-11e5-83cf-aaf31220cff6.png)
Where is the parameters section?

**Comment by JeffYounger** [comment]
Fixed.
