### ISSUE TITLE
DOCS - Pagination - Terminology Mixing count, totalCount, total

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#6]
Confusing when reading doc - count, totalCount, total are all used to mean "total" in the meta data.  Please consider using just total instead.

![general platform - pagination count vs total](https://cloud.githubusercontent.com/assets/13001388/8312123/994c61e0-19a0-11e5-8ca6-2a9ef38ab343.png)
![general platform pagination resource list pagination](https://cloud.githubusercontent.com/assets/13001388/8312124/9b764b52-19a0-11e5-8bad-1849ee7787ee.png)
![platform services device service list all devices](https://cloud.githubusercontent.com/assets/13001388/8312127/9e08ede8-19a0-11e5-8006-6c68ae34086e.png)

**Comment by JeffYounger** [comment]
Researched and fixed.
