### ISSUE TITLE
DOCS - Telemetry-service - Location-history: indefinite article has typo

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#7]
Under Request look for the "Since" bullet.  ... If an since value is not... the indefinite article "a" should be used in lieu of "an" as "since"  has a constant sound as the first character.
![telemetry services location-history](https://cloud.githubusercontent.com/assets/13001388/8335495/a79b5d78-1a63-11e5-9ff7-cffb06cc6172.png)

**Comment by JeffYounger** [comment]
Fixed.
