### ISSUE TITLE
DOCS - Telemetry Service Snapshot - Pagination example has typo

### ISSUE THREAD

**Issue by rubyb** [vinli/docs#8]
In the Response, meta data show limit set to 50.  Since it wasn't set on the request, it should be show the default value of 20 and not 50, right?
![telemetry service snapshot](https://cloud.githubusercontent.com/assets/13001388/8360264/4ceba8b4-1b31-11e5-8d7c-e1431985cd6a.png)

**Comment by JeffYounger** [comment]
Fixed.
